Repository CSC207-2022F-UofT/course-project-blue-guppies, pull requests merged in 2022-11, with the labels that each got.

#12 0 initial file structure setup
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  src/data_access/package-info.java
  src/entities/Day.java
  src/entities/Event.java
  src/entities/EventFactory.java
  src/entities/Task.java
  src/entities/TaskFactory.java
  src/entities/Week.java
  src/example_event_use_case/README.md
  src/main/java/HelloWorld.java
  src/main/java/Main.java
  src/screens/package-info.java
  src/test/java/tutorial/HelloWorldTest.java
  testing/example_event_use_case/README.md
Labels: good first issue

#18 11 Task Entity Implementation
  src/main/java/entities/Task.java
  src/main/java/entities/TaskFactory.java
  src/test/java/entities/TaskFactoryTest.java
  src/test/java/entities/TaskTest.java
Labels: documentation, enhancement

#21 Added Completed attribute to Task Entity
  src/main/java/entities/Task.java
  src/test/java/entities/TaskFactoryTest.java
  src/test/java/entities/TaskTest.java
Labels: bug

#34 Feature/controller test documentation
  README.md
Labels: documentation
