Repository CSC207-2022F-UofT/course-project-blue-guppies, pull requests merged in 2022-12, with the labels that each got.

#33 3 task deletion
  src/main/java/delete_task_use_case/DeleteTaskController.java
  src/main/java/delete_task_use_case/DeleteTaskDataAccess.java
  src/main/java/delete_task_use_case/DeleteTaskDsGateway.java
  src/main/java/delete_task_use_case/DeleteTaskDsInputData.java
  src/main/java/delete_task_use_case/DeleteTaskInputBoundary.java
  src/main/java/delete_task_use_case/DeleteTaskInputData.java
  src/main/java/delete_task_use_case/DeleteTaskInteractor.java
  src/main/java/delete_task_use_case/DeleteTaskOutputBoundary.java
  src/main/java/delete_task_use_case/DeleteTaskOutputData.java
  src/main/java/delete_task_use_case/DeleteTaskPresenter.java
  src/test/java/delete_task_use_case/DeleteTaskControllerTest.java
  src/test/java/delete_task_use_case/DeleteTaskDataAccessTest.java
  src/test/java/delete_task_use_case/DeleteTaskDsInputDataTest.java
  src/test/java/delete_task_use_case/DeleteTaskInputDataTest.java
  src/test/java/delete_task_use_case/DeleteTaskInteractorTest.java
  src/test/java/delete_task_use_case/DeleteTaskOutputDataTest.java
  src/test/java/delete_task_use_case/DeleteTaskPresenterTest.java
Labels: documentation, enhancement

#36 1 Task Creation
  .idea/misc.xml
  src/main/java/create_task_use_case/CreateTaskController.java
  src/main/java/create_task_use_case/CreateTaskDataAccess.java
  src/main/java/create_task_use_case/CreateTaskDsGateway.java
  src/main/java/create_task_use_case/CreateTaskDsInputData.java
  src/main/java/create_task_use_case/CreateTaskInputBoundary.java
  src/main/java/create_task_use_case/CreateTaskInputData.java
  src/main/java/create_task_use_case/CreateTaskInteractor.java
  src/main/java/create_task_use_case/CreateTaskOutputBoundary.java
  src/main/java/create_task_use_case/CreateTaskOutputData.java
  src/main/java/create_task_use_case/CreateTaskPresenter.java
  src/test/java/create_task_use_case/CreateTaskControllerTest.java
  src/test/java/create_task_use_case/CreateTaskDataAccessTest.java
  src/test/java/create_task_use_case/CreateTaskDsInputDataTest.java
  src/test/java/create_task_use_case/CreateTaskInputDataTest.java
  src/test/java/create_task_use_case/CreateTaskInteractorTest.java
  src/test/java/create_task_use_case/CreateTaskOutputDataTest.java
  src/test/java/create_task_use_case/CreateTaskPresenterTest.java
Labels: documentation, enhancement

#35 6 event deletion
  src/main/java/delete_event_use_case/DeleteEventController.java
  src/main/java/delete_event_use_case/DeleteEventDataAccess.java
  src/main/java/delete_event_use_case/DeleteEventDsGateway.java
  src/main/java/delete_event_use_case/DeleteEventInputBoundary.java
  src/main/java/delete_event_use_case/DeleteEventInputData.java
  src/main/java/delete_event_use_case/DeleteEventInteractor.java
  src/main/java/delete_event_use_case/DeleteEventOutputBoundary.java
  src/main/java/delete_event_use_case/DeleteEventOutputData.java
  src/main/java/delete_event_use_case/DeleteEventPresenter.java
  src/test/java/delete_event_use_case/DeleteEventControllerTest.java
  src/test/java/delete_event_use_case/DeleteEventDataAccessTest.java
  src/test/java/delete_event_use_case/DeleteEventInputDataTest.java
  src/test/java/delete_event_use_case/DeleteEventInteractorTest.java
  src/test/java/delete_event_use_case/DeleteEventOutputDataTest.java
  src/test/java/delete_event_use_case/DeleteEventPresenterTest.java
Labels: documentation, enhancement

#41 7 task Completion
  src/main/java/complete_task_use_case/CompleteTaskController.java
  src/main/java/complete_task_use_case/CompleteTaskDataAccess.java
  src/main/java/complete_task_use_case/CompleteTaskDsGateway.java
  src/main/java/complete_task_use_case/CompleteTaskDsInputData.java
  src/main/java/complete_task_use_case/CompleteTaskInputBoundary.java
  src/main/java/complete_task_use_case/CompleteTaskInputData.java
  src/main/java/complete_task_use_case/CompleteTaskInteractor.java
  src/main/java/complete_task_use_case/CompleteTaskOutputBoundary.java
  src/main/java/complete_task_use_case/CompleteTaskOutputData.java
  src/main/java/complete_task_use_case/CompleteTaskPresenter.java
  src/main/java/modify_task_use_case/example_event_use_case/DocumentationConventions.md
  src/main/java/modify_task_use_case/example_event_use_case/README.md
  src/test/java/complete_task_use_case/CompleteTaskControllerTest.java
  src/test/java/complete_task_use_case/CompleteTaskDataAccessTest.java
  src/test/java/complete_task_use_case/CompleteTaskDsInputDataTest.java
  src/test/java/complete_task_use_case/CompleteTaskInputDataTest.java
  src/test/java/complete_task_use_case/CompleteTaskInteractorTest.java
  src/test/java/complete_task_use_case/CompleteTaskOutputDataTest.java
  src/test/java/complete_task_use_case/CompleteTaskPresenterTest.java
  src/test/java/create_task_use_case/CreateTaskControllerTest.java
Labels: documentation, enhancement

#43 8 clear all
  src/main/java/clear_all_use_case/ClearAllController.java
  src/main/java/clear_all_use_case/ClearAllDataAccess.java
  src/main/java/clear_all_use_case/ClearAllDsGateway.java
  src/main/java/clear_all_use_case/ClearAllInputBoundary.java
  src/main/java/clear_all_use_case/ClearAllInteractor.java
  src/main/java/clear_all_use_case/ClearAllOutputBoundary.java
  src/main/java/clear_all_use_case/ClearAllOutputData.java
  src/main/java/clear_all_use_case/ClearAllPresenter.java
  src/test/java/clear_all_use_case/ClearAllControllerTest.java
  src/test/java/clear_all_use_case/ClearAllDataAccessTest.java
  src/test/java/clear_all_use_case/ClearAllInteractorTest.java
  src/test/java/clear_all_use_case/ClearAllOutputDataTest.java
  src/test/java/clear_all_use_case/ClearAllPresenterTest.java
Labels: documentation, enhancement

#44 9 UI
  src/main/java/Main.java
  src/main/java/create_event_use_case/CreateEventController.java
  src/main/java/create_event_use_case/CreateEventDataAccess.java
  src/main/java/create_event_use_case/CreateEventDsGateway.java
  src/main/java/create_event_use_case/CreateEventInputBoundary.java
  src/main/java/create_event_use_case/CreateEventInputData.java
  src/main/java/create_event_use_case/CreateEventInteractor.java
  src/main/java/create_event_use_case/CreateEventOutputBoundary.java
  src/main/java/create_event_use_case/CreateEventOutputData.java
  src/main/java/create_event_use_case/CreateEventPresenter.java
  src/main/java/data_access/WeekDataAccess.java
  src/main/java/screens/ClickEventScreen.java
  src/main/java/screens/ClickTaskScreen.java
  src/main/java/screens/CreateEventScreen.java
  src/main/java/screens/CreateTaskScreen.java
  src/main/java/screens/FormScreen.java
  src/main/java/screens/ModifyEventScreen.java
  src/main/java/screens/ModifyTaskScreen.java
  src/main/java/screens/WeekViewScreen.java
  src/main/java/screens/package-info.java
Labels: enhancement

#45 4 event creation
  src/main/java/create_event_use_case/CreateEventController.java
  src/main/java/create_event_use_case/CreateEventDataAccess.java
  src/main/java/create_event_use_case/CreateEventDsGateway.java
  src/main/java/create_event_use_case/CreateEventDsInputData.java
  src/main/java/create_event_use_case/CreateEventInputBoundary.java
  src/main/java/create_event_use_case/CreateEventInputData.java
  src/main/java/create_event_use_case/CreateEventInteractor.java
  src/main/java/create_event_use_case/CreateEventOutputBoundary.java
  src/main/java/create_event_use_case/CreateEventOutputData.java
  src/main/java/create_event_use_case/CreateEventPresenter.java
  src/main/java/data_access/WeekDataAccess.java
  src/main/java/screens/CreateEventScreen.java
  src/test/java/create_event_use_case/CreateEventControllerTest.java
  src/test/java/create_event_use_case/CreateEventDataAccessTest.java
  src/test/java/create_event_use_case/CreateEventDsInputDataTest.java
  src/test/java/create_event_use_case/CreateEventInputDataTest.java
  src/test/java/create_event_use_case/CreateEventInteractorTest.java
  src/test/java/create_event_use_case/CreateEventOutputDataTest.java
  src/test/java/create_event_use_case/CreateEventPresenterTest.java
Labels: enhancement

#49 32 Complete Task Use Case 100% Test Coverage
  src/test/java/complete_task_use_case/CompleteTaskInteractorTest.java
Labels: enhancement

#52 33. Add Completed Status to data models
  src/main/java/complete_task_use_case/CompleteTaskController.java
  src/main/java/complete_task_use_case/CompleteTaskDsInputData.java
  src/main/java/complete_task_use_case/CompleteTaskInputData.java
  src/main/java/complete_task_use_case/CompleteTaskInteractor.java
  src/main/java/complete_task_use_case/CompleteTaskOutputData.java
  src/main/java/complete_task_use_case/CompleteTaskPresenter.java
  src/main/java/screens/ClickTaskScreen.java
  src/test/java/complete_task_use_case/CompleteTaskControllerTest.java
  src/test/java/complete_task_use_case/CompleteTaskDataAccessTest.java
  src/test/java/complete_task_use_case/CompleteTaskDsInputDataTest.java
  src/test/java/complete_task_use_case/CompleteTaskInputDataTest.java
  src/test/java/complete_task_use_case/CompleteTaskInteractorTest.java
  src/test/java/complete_task_use_case/CompleteTaskOutputDataTest.java
  src/test/java/complete_task_use_case/CompleteTaskPresenterTest.java
Labels: bug

#53 30 setup view model
  src/main/java/Main.java
  src/main/java/clear_all_use_case/ClearAllPresenter.java
  src/main/java/complete_task_use_case/CompleteTaskOutputData.java
  src/main/java/complete_task_use_case/CompleteTaskPresenter.java
  src/main/java/create_event_use_case/CreateEventPresenter.java
  src/main/java/create_task_use_case/CreateTaskPresenter.java
  src/main/java/delete_event_use_case/DeleteEventOutputData.java
  src/main/java/delete_event_use_case/DeleteEventPresenter.java
  src/main/java/delete_task_use_case/DeleteTaskPresenter.java
  src/main/java/modify_event_use_case/ModifyEventPresenter.java
  src/main/java/modify_task_use_case/ModifyTaskInteractor.java
  src/main/java/modify_task_use_case/ModifyTaskOutputData.java
  src/main/java/modify_task_use_case/ModifyTaskPresenter.java
  src/main/java/modify_task_use_case/example_event_use_case/DocumentationConventions.md
  src/main/java/modify_task_use_case/example_event_use_case/README.md
  src/main/java/screens/ModifyEventScreen.java
  src/main/java/screens/ViewModel.java
  src/main/java/screens/ViewModelBoundary.java
  src/main/java/screens/ViewModelObserver.java
  src/main/java/screens/WeekViewScreen.java
  src/test/java/modify_task_use_case/ModifyTaskOutputBoundaryTest.java
  src/test/java/modify_task_use_case/ModifyTaskOutputDataTest.java
  src/test/java/modify_task_use_case/ModifyTaskPresenterTest.java
Labels: enhancement

#60 35 Day to DayIndex Conversion
  .idea/misc.xml
  src/main/java/create_event_use_case/CreateEventController.java
  src/main/java/create_event_use_case/CreateEventInputData.java
  src/main/java/create_task_use_case/CreateTaskController.java
  src/main/java/create_task_use_case/CreateTaskInputData.java
  src/main/java/screens/ViewModel.java
  src/test/java/create_event_use_case/CreateEventInputDataTest.java
  src/test/java/create_event_use_case/CreateEventInteractorTest.java
  src/test/java/create_task_use_case/CreateTaskInputDataTest.java
  src/test/java/create_task_use_case/CreateTaskInteractorTest.java
Labels: enhancement

#65 63 add readme
  README.md
  images/ClearWeek.gif
  images/CompleteTask.gif
  images/CreateEvent.gif
  images/CreateTask.gif
  images/DeleteEvent.gif
  images/DeleteTask.gif
  images/ModifyEvent.gif
  images/ModifyTask.gif
  images/closed_issue.png
  images/closed_project.png
  images/create_branch.png
  images/create_pr.png
  images/create_project.png
  images/link_branch.png
  images/link_project.png
  images/new_issue.png
  images/new_pr.png
  images/rename.png
  images/set_tags.png
Labels: documentation

#62 57 Address Warnings and Typos or Document
  CleanCalendarStorage.txt
  README.md
  project_plan_dev.md
  src/main/java/Main.java
  src/main/java/complete_task_use_case/CompleteTaskDsInputData.java
  src/main/java/complete_task_use_case/CompleteTaskInputData.java
  src/main/java/complete_task_use_case/CompleteTaskInteractor.java
  src/main/java/data_access/WeekDataAccess.java
  src/main/java/delete_task_use_case/DeleteTaskDataAccess.java
  src/main/java/delete_task_use_case/DeleteTaskInteractor.java
  src/main/java/modify_event_use_case/ModifyEventController.java
  src/main/java/modify_event_use_case/ModifyEventInteractor.java
  src/main/java/modify_event_use_case/ModifyEventOutputData.java
  src/main/java/modify_task_use_case/ModifyTaskInteractor.java
  src/main/java/screens/ClickTaskScreen.java
  src/main/java/screens/CreateEventScreen.java
  src/main/java/screens/CreateTaskScreen.java
  src/test/example_event_use_case/README.md
  src/test/java/complete_task_use_case/CompleteTaskDataAccessTest.java
  src/test/java/complete_task_use_case/CompleteTaskDsInputDataTest.java
  src/test/java/complete_task_use_case/CompleteTaskInputDataTest.java
  src/test/java/complete_task_use_case/CompleteTaskInteractorTest.java
  src/test/java/create_event_use_case/CreateEventDataAccessTest.java
  src/test/java/create_event_use_case/CreateEventDsInputDataTest.java
  src/test/java/create_event_use_case/CreateEventOutputDataTest.java
  src/test/java/create_task_use_case/CreateTaskInteractorTest.java
  src/test/java/delete_event_use_case/DeleteEventDataAccessTest.java
  src/test/java/delete_event_use_case/DeleteEventInputDataTest.java
  src/test/java/entities/DayFactoryTest.java
  src/test/java/modify_event_use_case/ModifyEventControllerTest.java
  src/test/java/modify_event_use_case/ModifyEventDataAccessTest.java
  src/test/java/modify_event_use_case/ModifyEventDsInputDataTest.java
  src/test/java/modify_event_use_case/ModifyEventInputDataTest.java
  src/test/java/modify_event_use_case/ModifyEventInteractorTest.java
  src/test/java/modify_event_use_case/ModifyEventOutputDataTest.java
  src/test/java/modify_event_use_case/ModifyEventPresenterTest.java
Labels: documentation, enhancement

#69 68 factory and strategy changes
  CleanCalendarStorage.txt
  src/main/java/Main.java
  src/main/java/create_event_use_case/CreateEventController.java
  src/main/java/create_event_use_case/CreateEventInteractor.java
  src/main/java/create_task_use_case/CreateTaskController.java
  src/main/java/create_task_use_case/CreateTaskInteractor.java
  src/main/java/entities/DayFactory.java
  src/main/java/entities/EventFactory.java
  src/main/java/entities/TaskFactory.java
  src/main/java/entities/WeekFactory.java
  src/main/java/strategies/DayToIndexConverter.java
  src/main/java/strategies/SaturdayAssumingConverter.java
  src/test/java/create_event_use_case/CreateEventControllerTest.java
  src/test/java/create_event_use_case/CreateEventDataAccessTest.java
  src/test/java/create_event_use_case/CreateEventDsInputDataTest.java
  src/test/java/create_event_use_case/CreateEventInteractorTest.java
  src/test/java/create_task_use_case/CreateTaskControllerTest.java
  src/test/java/create_task_use_case/CreateTaskInteractorTest.java
  src/test/java/entities/DayFactoryTest.java
  src/test/java/entities/EventFactoryTest.java
  src/test/java/entities/TaskFactoryTest.java
  src/test/java/entities/WeekFactoryTest.java
  src/test/java/strategies/SaturdayAssumingConverterTest.java
Labels: enhancement
